### ISSUE TITLE
本地运行Int4版本报错

### ISSUE THREAD

**Issue by ysyx2008** [OpenBMB/MiniCPM-V#132]
本地运行int4版本时候出现报错：

(MiniCPMV) yushen@user-MS-7E06:~/ai/MiniCPM-V$ python web_demo_2.5_gy.py --device cuda
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
Traceback (most recent call last):
  File "/home/yushen/ai/MiniCPM-V/web_demo_2.5_gy.py", line 32, in <module>
    model = AutoModel.from_pretrained(model_path, trust_remote_code=True)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3155, in from_pretrained
    config.quantization_config = AutoHfQuantizer.merge_quantization_configs(
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/transformers/quantizers/auto.py", line 149, in merge_quantization_configs
    quantization_config = AutoQuantizationConfig.from_dict(quantization_config)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/transformers/quantizers/auto.py", line 79, in from_dict
    return target_cls.from_dict(quantization_config_dict)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 94, in from_dict
    config = cls(**config_dict)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 284, in __init__
    self.post_init()
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/transformers/utils/quantization_config.py", line 342, in post_init
    if self.load_in_4bit and not version.parse(importlib.metadata.version("bitsandbytes")) >= version.parse(
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for bitsandbytes

**Comment by iceflame89** [comment]
pip install bitsandbytes

**Comment by ysyx2008** [comment]
> pip install bitsandbytes

感谢帮助，成功了。
