### ISSUE TITLE
图片无法上传。系统报错权限被拒绝。

### ISSUE THREAD

**Issue by ysyx2008** [OpenBMB/MiniCPM-V#133]
--------
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/gradio/route_utils.py", line 695, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/gradio/route_utils.py", line 711, in simple_response
    await self.app(scope, receive, send)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/site-packages/gradio/routes.py", line 998, in upload_file
    directory.mkdir(exist_ok=True, parents=True)
  File "/home/yushen/micromamba/envs/MiniCPMV/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/tmp/gradio/0115b4a4eb57645c024a02f1a08e62fa7924d5aa'

**Comment by ysyx2008** [comment]
是否必须root用户？

**Comment by iceflame89** [comment]
不必须root，请把/tmp目录改成公共可写权限

**Comment by ysyx2008** [comment]
感谢帮助，确实是gradio目录的权限问题，使用以下命令后恢复正常了~

sudo chmod a+w /tmp/gradio
