### ISSUE TITLE
[BUG] <title>关于数据集构建过程报错

### ISSUE THREAD

**Issue by Get-David** [OpenBMB/MiniCPM-V#211]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

```bash
(minicpmv) zdw@ai-gpu-server149:~/large_model/MiniCPM-V/finetune$ sh finetune_lora.sh 
[2024-06-04 15:53:49,811] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  async_io: please install the libaio-dev package with apt
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.1
 [WARNING]  using untested triton version (2.1.0), only 1.0.0 is known to be compatible
[2024-06-04 15:53:51,487] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-06-04 15:53:51,487] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:01<00:00,  3.51it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Currently using LoRA for fine-tuning the MiniCPM-V model.
{'Total': 8564355312, 'Trainable': 1059430640}
llm_type=minicpm
Loading data...
max_steps is given, it will override any value given in num_train_epochs
Using /home/zdw/.cache/torch_extensions/py310_cu121 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/zdw/.cache/torch_extensions/py310_cu121/fused_adam/build.ninja...
Building extension module fused_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_adam...
Time to load fused_adam op: 0.09214949607849121 seconds
  0%|                                                                                                                        | 0/10000 [00:00<?, ?it/s]image start token != image end tokens
Traceback (most recent call last):
  File "/home/zdw/large_model/MiniCPM-V/finetune/finetune.py", line 315, in <module>
    train()
  File "/home/zdw/large_model/MiniCPM-V/finetune/finetune.py", line 305, in train
    trainer.train()
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/transformers/trainer.py", line 2165, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/accelerate/data_loader.py", line 454, in __iter__
    current_batch = next(dataloader_iter)
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 674, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zdw/large_model/MiniCPM-V/finetune/dataset.py", line 46, in __getitem__
    ret = preprocess(
  File "/home/zdw/large_model/MiniCPM-V/finetune/dataset.py", line 288, in preprocess
    input_dict = conversation_to_ids(conversation, tokenizer, llm_type)
  File "/home/zdw/large_model/MiniCPM-V/finetune/dataset.py", line 144, in conversation_to_ids
    image_bound = torch.hstack(
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 4 but got size 5 for tensor number 1 in the list.
  0%|                                                                                                                        | 0/10000 [00:00<?, ?it/s]
[2024-06-04 15:54:06,394] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2042355) of binary: /data/share8/zdw/miniconda3/envs/minicpmv/bin/python
Traceback (most recent call last):
  File "/data/share8/zdw/miniconda3/envs/minicpmv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/share8/zdw/miniconda3/envs/minicpmv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-04_15:54:06
  host      : ai-gpu-server149
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2042355)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
(minicpmv) zdw@ai-gpu-server149:~/large_model/MiniCPM-V/finetune$ 
```
这是我的数据集文件的内容：
[
    {
        "id": "0",
        "image": "/home/zdw/large_model/data/piht/10.png",
        "conversations": [
            {
                "role": "user",
                "content": "<image>\nHow many desserts are on the white plate?"
            },
            {
                "role": "assistant",
                "content": "There are three desserts on the white plate."
            }
        ]
    },
    {
        "id": "1",
        "image": "/home/zdw/large_model/data/piht/11.png",
        "conversations": [
            {
                "role": "user",
                "content": "<image>\nHow many desserts are on the white plate?"
            },
            {
                "role": "assistant",
                "content": "There are three desserts on the white plate."
            }
        ]
    },
    {
        "id": "2",
        "image": "/home/zdw/large_model/data/piht/12.png",
        "conversations": [
            {
                "role": "user",
                "content": "<image>\nHow many desserts are on the white plate?"
            },
            {
                "role": "assistant",
                "content": "There are three desserts on the white plate."
            }
        ]
    },
    {
        "id": "3",
        "image": "/home/zdw/large_model/data/piht/13.png",
        "conversations": [
            {
                "role": "user",
                "content": "<image>\nHow many desserts are on the white plate?"
            },
            {
                "role": "assistant",
                "content": "There are three desserts on the white plate."
            }
        ]
    },
    {
        "id": "4",
        "image": "/home/zdw/large_model/data/piht/14.png",
        "conversations": [
            {
                "role": "user",
                "content": "<image>\nHow many desserts are on the white plate?"
            },
            {
                "role": "assistant",
                "content": "There are three desserts on the white plate."
            }
        ]
    },
    {
        "id": "5",
        "image": "/home/zdw/large_model/data/piht/15.png",
        "conversations": [
            {
                "role": "user",
                "content": "<image>\nHow many desserts are on the white plate?"
            },
            {
                "role": "assistant",
                "content": "There are three desserts on the white plate."
            }
        ]
    }
]

### 运行环境 | Environment

```Markdown
- OS:
- Python:
- Transformers:
- PyTorch:
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):
```

**Comment by GoldfishFive** [comment]
我也遇到了类似问题，请问您是怎么解决的

**Comment by Get-David** [comment]
> 我也遇到了类似问题，请问您是怎么解决的

配置里从minicpm换成了llama3
```bash
LLM_TYPE="llama3" # if use openbmb/MiniCPM-V-2, please set LLM_TYPE=minicpm
```

**Comment by limllzu** [comment]
你好，请问解决了吗，我也遇到了这个问题

**Comment by Get-David** [comment]
> 你好，请问解决了吗，我也遇到了这个问题

不是数据集的问题，是模型类型选错了
