### ISSUE TITLE
[BUG] <title>MiniCPM-V2.0不支持zero3全量微调

### ISSUE THREAD

**Issue by daihuidai** [OpenBMB/MiniCPM-V#268]
一台机器，两张4090；一台机器，两张3090

v2.0在zero2下使用lora或者不适用lora仅训练vpm+resampler都是没问题的，但是一旦改成zero3就会报错；这个问题似乎只在v2.0上有。当我训练MiniCPM-V2.5使用zero3时可以正常运行并没有什么问题。
所以我觉得这可能是v2.0使用zero3的bug，在群里反馈也有人遇到同样的问题，不知道是否可以解决下。

**Comment by 1SingleFeng** [comment]
您好，您说的是哪个群，请问能分享一下吗

**Comment by daihuidai** [comment]
@1SingleFeng MiniCPM他们自己提供的微信群

**Comment by daihuidai** [comment]
@1SingleFeng 你好，就是MiniCPM-V-16群。报下面这个错：

Traceback (most recent call last):
  File "/home/project/CPM/MiniCPM-V/finetune/finetune.py", line 330, in <module>
    train()
  File "/home/project/CPM/MiniCPM-V/finetune/finetune.py", line 320, in train
    trainer.train()         # trainer.train(resume_from_checkpoint=True)
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/project/CPM/MiniCPM-V/finetune/trainer.py", line 206, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/project/CPM/MiniCPM-V/finetune/trainer.py", line 21, in compute_loss
    outputs = self.model(data = inputs, use_cache=False)
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/.cache/huggingface/modules/transformers_modules/MiniCPM-V-2/modeling_minicpmv.py", line 141, in forward
    vllm_embedding, vision_hidden_states = self.get_vllm_embedding(data)
  File "/home/.cache/huggingface/modules/transformers_modules/MiniCPM-V-2/modeling_minicpmv.py", line 94, in get_vllm_embedding
    vision_hidden_states.append(self.get_vision_embedding(pixel_values))
  File "/home/.cache/huggingface/modules/transformers_modules/MiniCPM-V-2/modeling_minicpmv.py", line 82, in get_vision_embedding
    vision_embedding = self.vpm.forward_features(pixel_value.unsqueeze(0).type(dtype))
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/timm/models/vision_transformer.py", line 663, in forward_features
    x = self._pos_embed(x)
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/timm/models/vision_transformer.py", line 582, in _pos_embed
    pos_embed = resample_abs_pos_embed(
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/timm/layers/pos_embed.py", line 27, in resample_abs_pos_embed
    num_pos_tokens = posemb.shape[1]
IndexError: tuple index out of range
  0%|                                                                | 0/10000 [00:01<?, ?it/s]
[2024-06-17 10:42:35,698] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 144191 closing signal SIGTERM
[2024-06-17 10:42:35,762] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 144190) of binary: /home/hncy/anaconda3/envs/MiniCPMV/bin/python
Traceback (most recent call last):
  File "/home/anaconda3/envs/MiniCPMV/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/anaconda3/envs/MiniCPMV/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-06-17_10:42:35
  host      : hncy-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 144190)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by qyc-98** [comment]
您好这个是代码问题，我们会更新huggingface的代码，如果着急您可以直接前往页面找到对应的pr修改自己的模型文件进行微调

**Comment by daihuidai** [comment]
感谢回复，期待你们的更新，我这边也找对应pr尝试下

**Comment by daihuidai** [comment]
@1SingleFeng 你好，我根据pr修改了两个文件的代码出现了新的报错信息：
![image](https://github.com/OpenBMB/MiniCPM-V/assets/43409147/ff38f787-8611-4181-aac6-e7fa6923c41c)

这似乎是模型的张量处理的问题，请问是哪里的问题呢

**Comment by 1SingleFeng** [comment]
> @1SingleFeng 你好，我根据pr修改了两个文件的代码出现了新的报错信息： ![image](https://private-user-images.githubusercontent.com/43409147/340229367-ff38f787-8611-4181-aac6-e7fa6923c41c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2MTI0MjQsIm5iZiI6MTcxODYxMjEyNCwicGF0aCI6Ii80MzQwOTE0Ny8zNDAyMjkzNjctZmYzOGY3ODctODYxMS00MTgxLWFhYzYtZTdmYTY5MjNjNDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDA4MTUyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3NGMzN2MyZjk3ZDM0NWNmOTQyMjIzNGRkZDVjYjg5NGIwNmNlNjcwOWFjMmQ3OGQ2ZDA5YmQxMmUxZGIwZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fGr-Rbjqj5t7DHFGUH1rmJionG9eMpLlaUSkUNr8-ys)
> 
> 这似乎是模型的张量处理的问题，请问是哪里的问题呢

你好，我暂时用不上minicpmv-2，所以对这些问题不太了解

**Comment by daihuidai** [comment]
@qyc-98 你好，请问上面这个报错是新代码的问题还是，什么原因呢

**Comment by qyc-98** [comment]
您好 如果您使用的是minicpmv2 您可以参考咱们这个仓库里的pr，里面对trainer等部分做了修改 https://github.com/OpenBMB/MiniCPM-V/pull/273

**Comment by daihuidai** [comment]
@qyc-98 你好，我按照pr也修改了trainer，这边依旧还是报上面第一个RunningError错误，但并没有出现后面的AssertionError错误，我检查了修改代码确实是按照pr的修改了，目前希望官方能够早点更新整体代码吧

**Comment by qyc-98** [comment]
你的bug是什么

**Comment by daihuidai** [comment]
@qyc-98  目前的报错信息如下：
![image](https://github.com/OpenBMB/MiniCPM-V/assets/43409147/b882e971-4fb4-4909-a943-a4306a75c00a)

我的ds.sh参数如下：
![image](https://github.com/OpenBMB/MiniCPM-V/assets/43409147/3a25e290-35b0-4645-81ff-bbed14491bc3)


没有出现之前的AssertionError错误了。

**Comment by MrToy** [comment]
bump, finetune with swift

**Comment by qyc-98** [comment]
@daihuidai  您好我目前对代码做了修改，这个bug的原因是vpm的pos_embed没有被deepspeed调用起来，导致forward和backward都需要强制的召唤这部分参数，模型代码里我们进行了修改，但是在trainer的代码里也需要做修改，目前我自己的pr是做了这个修改 你可以参考这个 https://github.com/OpenBMB/MiniCPM-V/pull/273，后续我们会更新到主分支里
I have made some modifications to the code. The cause of the bug was that the pos_embed of the VPM was not being invoked by DeepSpeed, resulting in both the forward and backward passes requiring explicit calls to this part of the parameters. We have made modifications in the model code, but changes are also needed in the trainer code. I have already made these changes in my pull request, which has been successfully executed. You can refer to it. We will update it to the main branch subsequently.

**Comment by daihuidai** [comment]
@qyc-98 你好，我似乎又发现问题了......，我按照最新的pr又修改了trainer的代码，目前并没有报错直接退出程序，但是出现了下面的报错信息，导致打印日志卡死在这里，并且显存一直被占用但没有变化，估计是程序卡死了。
![image](https://github.com/OpenBMB/MiniCPM-V/assets/43409147/b54824c4-0542-4f03-80d0-5b6214df2986)

**Comment by daihuidai** [comment]
@MrToy 你好，我试过swift，可以lora，但是没法full finetune，我是一台机器两张卡，当swift使用--lora_target_modules ALL --deepspeed default-zero3时会报错一台机器无法使用。

**Comment by daihuidai** [comment]
@qyc-98 请问Minicpmv2.0对zero3的支持有新的更新了吗

**Comment by DwanZhang-AI** [comment]
请问下解决了嘛？
