### ISSUE TITLE
[BUG] 最新代码微调lora报错

### ISSUE THREAD

**Issue by MrChen314** [OpenBMB/MiniCPM-V#348]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

使用最新的finetune.py（7.18晚刚刚更新的），进行lora微调报错如下：
Traceback (most recent call last):
  File "/data1/c30061641/MiniCPM-V/finetune/finetune.py", line 285, in <module>
    train()
  File "/data1/c30061641/MiniCPM-V/finetune/finetune.py", line 275, in train
    trainer.train()
  File "/root/miniconda3/envs/MiniCPM-V/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/MiniCPM-V/lib/python3.10/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/data1/c30061641/MiniCPM-V/finetune/trainer.py", line 198, in training_step
    loss = self.compute_loss(model, inputs)
  File "/data1/c30061641/MiniCPM-V/finetune/trainer.py", line 22, in compute_loss
    outputs = self.model.base_model(data = inputs, use_cache=False)
  File "/root/miniconda3/envs/MiniCPM-V/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/MiniCPM-V/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/MiniCPM-V/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 179, in forward
    return self.model.forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/model/modeling_minicpmv.py", line 164, in forward
    vllm_embedding, vision_hidden_states = self.get_vllm_embedding(data)
  File "/root/.cache/huggingface/modules/transformers_modules/model/modeling_minicpmv.py", line 72, in get_vllm_embedding
    dtype = self.vpm.embeddings.position_embedding.weight.dtype
  File "/root/miniconda3/envs/MiniCPM-V/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'ModulesToSaveWrapper' object has no attribute 'embeddings'

### 期望行为 | Expected Behavior

lora微调正常训练

### 复现方法 | Steps To Reproduce

fintune_lora.sh

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04.1 LTS
- Python:3.10.0
- Transformers:4.40.0
- PyTorch:2.1.2+cu121
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by MrChen314** [comment]
谢谢，您的邮件已收到，我会尽快处理

**Comment by zysNLP** [comment]
我也遇到了同样的问题，用全量微调就不会报这个错，但是lora就会，有些奇怪，File "/root/miniconda3/envs/MiniCPM-V/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in getattr
raise AttributeError(f"'{type(self).name}' object has no attribute '{name}'")
AttributeError: 'ModulesToSaveWrapper' object has no attribute 'embeddings'。看错误日志好像是torch模块的问题？难道官方requirements.txt中的torch=2.1.2的版本不对吗？全量微调会OOM，所以还是想用lora，请帮忙看一下这个问题，多谢！

**Comment by MrChen314** [comment]
huggingface上模型代码更新了，更新代码后就OK了

**Comment by zysNLP** [comment]
@MrChen314 您指的更新谁的代码？transfomers模块吗？

**Comment by zysNLP** [comment]
哦哦看到了，模型文件夹里的py文件
