### ISSUE TITLE
When running web_demo_2.6.py, It outputs TypeError: ModelScopeMultimodalInput.__init__() got an unexpected keyword argument 'upload_image_button_props'[BUG] <title>

### ISSUE THREAD

**Issue by Labmem009** [OpenBMB/MiniCPM-V#407]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

run CUDA_VISIBLE_DEVICES=2 python web_demo_2.6.py 
it outputs :
Traceback (most recent call last):
  File "/MiniCPM-V-main/web_demo_2.6.py", line 481, in <module>
    txt_message = create_multimodal_input()
  File "/MiniCPM-V-main/web_demo_2.6.py", line 126, in create_multimodal_input
    return mgr.MultimodalInput(upload_image_button_props={'label': 'Upload Image', 'disabled': upload_image_disabled, 'file_count': 'multiple'},
  File "/anaconda3/envs/MiniCPM-V/lib/python3.10/site-packages/gradio/component_meta.py", line 159, in wrapper
    return fn(self, **kwargs)
TypeError: ModelScopeMultimodalInput.__init__() got an unexpected keyword argument 'upload_image_button_props'

### 期望行为 | Expected Behavior

What caused this error? How to solve it?

### 运行环境 | Environment

```Markdown
pip show modelscope_studio
Name: modelscope_studio
Version: 0.4.0
```

**Comment by Labmem009** [comment]
reinstall with http://thunlp.oss-cn-qingdao.aliyuncs.com/multi_modal/never_delete/modelscope_studio-0.4.0.9-py3-none-any.whl can solve it
