### ISSUE TITLE
[BUG] ValueError: BitAndBytes with enforce_eager = False is not supported yet.

### ISSUE THREAD

**Issue by zjy1412** [OpenBMB/MiniCPM-V#427]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

我使用 _vllm==0.5.4_  运行 _MiniCPM-V-2_6-int4_ ，在运行时遇到如标题所示报错，这个报错我在[vllm那边](https://github.com/vllm-project/vllm/issues/7294)那边也有看到，完整日志如下：
```shell
$ python test.py
WARNING 08-08 17:18:49 config.py:254] bitsandbytes quantization is not fully optimized yet. The speed can be slower than non-quantized models.
Traceback (most recent call last):
  File "/home/zjy1412/projects/minicpm/test.py", line 20, in <module>
    llm = LLM(model=MODEL_NAME,
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjy1412/anaconda3/envs/cpm/lib/python3.12/site-packages/vllm/entrypoints/llm.py", line 158, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjy1412/anaconda3/envs/cpm/lib/python3.12/site-packages/vllm/engine/llm_engine.py", line 442, in from_engine_args
    engine_config = engine_args.create_engine_config()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zjy1412/anaconda3/envs/cpm/lib/python3.12/site-packages/vllm/engine/arg_utils.py", line 862, in create_engine_config
    return EngineConfig(
           ^^^^^^^^^^^^^
  File "<string>", line 15, in __init__
  File "/home/zjy1412/anaconda3/envs/cpm/lib/python3.12/site-packages/vllm/config.py", line 1641, in __post_init__
    self.model_config.verify_with_parallel_config(self.parallel_config)
  File "/home/zjy1412/anaconda3/envs/cpm/lib/python3.12/site-packages/vllm/config.py", line 293, in verify_with_parallel_config
    raise ValueError(
ValueError: BitAndBytes with enforce_eager = False is not supported yet.
```

### 运行环境 | Environment

```Markdown
- OS:Debian
- Python:3.12.4
- Transformers:4.44.0
- PyTorch:2.4.0
- CUDA:12.1
```

**Comment by DLBob** [comment]
同上，在部署4bit模型是遇到同样的问题

**Comment by zjy1412** [comment]
这个问题的[解决方案](https://github.com/vllm-project/vllm/commit/a049b107e207db796817fb83c4536e0625531d54)已经合并到vllm的主分支了。

**Comment by seasoncool** [comment]
@zjy1412  請教下，這是要等待 VLLM的官方更新嗎？才能再使用嗎 ？
