### ISSUE TITLE
[BUG] 微调MiniCPM-V 2.0 报错：IndexError: tuple index out of range

### ISSUE THREAD

**Issue by baibaiw5** [OpenBMB/MiniCPM-V#458]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 该问题是否在FAQ中有解答？ | Is there an existing answer for this in FAQ?

- [X] 我已经搜索过FAQ | I have searched FAQ

### 当前行为 | Current Behavior

Traceback (most recent call last):
  File "/home/bmb/projects/MiniCPM-V/finetune/finetune.py", line 296, in <module>
    train()
  File "/home/bmb/projects/MiniCPM-V/finetune/finetune.py", line 286, in train
    trainer.train()
  File "/home/bmb/anaconda3/envs/minicpm/lib/python3.10/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/home/bmb/anaconda3/envs/minicpm/lib/python3.10/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/bmb/projects/MiniCPM-V/finetune/trainer.py", line 199, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/bmb/projects/MiniCPM-V/finetune/trainer.py", line 20, in compute_loss
    outputs = self.model(data = inputs, use_cache=False)
  File "/home/bmb/anaconda3/envs/minicpm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/bmb/anaconda3/envs/minicpm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/bmb/.cache/huggingface/modules/transformers_modules/ee00ff7ce36667e7df81cb2a018951b663bdcc59/modeling_minicpmv.py", line 155, in forward
    vllm_embedding, vision_hidden_states = self.get_vllm_embedding(data)
  File "/home/bmb/.cache/huggingface/modules/transformers_modules/ee00ff7ce36667e7df81cb2a018951b663bdcc59/modeling_minicpmv.py", line 108, in get_vllm_embedding
    vision_hidden_states.append(self.get_vision_embedding(pixel_values))
  File "/home/bmb/.cache/huggingface/modules/transformers_modules/ee00ff7ce36667e7df81cb2a018951b663bdcc59/modeling_minicpmv.py", line 98, in get_vision_embedding
    result = process_each_pixel(pixel_value, dtype, self.config, self.vpm, self.resampler)
  File "/home/bmb/.cache/huggingface/modules/transformers_modules/ee00ff7ce36667e7df81cb2a018951b663bdcc59/modeling_minicpmv.py", line 91, in process_each_pixel
    vision_embedding = self.vpm_forward_features(pixel_value.unsqueeze(0).type(dtype))
  File "/home/bmb/.cache/huggingface/modules/transformers_modules/ee00ff7ce36667e7df81cb2a018951b663bdcc59/modeling_minicpmv.py", line 83, in vpm_forward_features
    return self.vpm.forward_features(pixel_value)
  File "/home/bmb/anaconda3/envs/minicpm/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 663, in forward_features
    x = self._pos_embed(x)
  File "/home/bmb/anaconda3/envs/minicpm/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 582, in _pos_embed
    pos_embed = resample_abs_pos_embed(
  File "/home/bmb/anaconda3/envs/minicpm/lib/python3.10/site-packages/timm/layers/pos_embed.py", line 27, in resample_abs_pos_embed
    num_pos_tokens = posemb.shape[1]
IndexError: tuple index out of range

### 期望行为 | Expected Behavior

按照教程微调MiniCPM-V 2.0能成功。

### 复现方法 | Steps To Reproduce

# 安装
git clone https://github.com/OpenBMB/MiniCPM-V.git 
pip install -r requirements.txt
pip install timm==0.9.10
pip install peft==0.12.0
pip install tensorboardX
pip install deepspeed==0.13.5

# 训练
参考教程：https://github.com/OpenBMB/MiniCPM-V/blob/main/finetune/readme.md
启动：
GPUS_PER_NODE=8
NNODES=1
NODE_RANK=0
MASTER_ADDR=localhost
MASTER_PORT=6001

MODEL="openbmb/MiniCPM-V-2"
# or openbmb/MiniCPM-V-2, openbmb/MiniCPM-Llama3-V-2_5
# ATTENTION: specify the path to your training data, which should be a json file consisting of a list of conversations.
# See the section for finetuning in README for more information.
DATA="path/to/trainging_data"
EVAL_DATA="path/to/test_data"
LLM_TYPE="minicpm" # 

DISTRIBUTED_ARGS="
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --node_rank $NODE_RANK \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT
"
torchrun $DISTRIBUTED_ARGS finetune.py  \
    --model_name_or_path $MODEL \
    --llm_type $LLM_TYPE \
    --data_path $DATA \
    --eval_data_path $EVAL_DATA \
    --remove_unused_columns false \
    --label_names "labels" \
    --prediction_loss_only false \
    --bf16 true \
    --bf16_full_eval true \
    --fp16 false \
    --fp16_full_eval false \
    --do_train \
    --do_eval \
    --tune_vision true \
    --tune_llm true \
    --model_max_length 2048 \
    --max_slice_nums 9 \
    --max_steps 10000 \
    --eval_steps 1000 \
    --output_dir output/output_minicpmv26 \
    --logging_dir output/output_minicpmv26 \
    --logging_strategy "steps" \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "steps" \
    --save_strategy "steps" \
    --save_steps 1000 \
    --save_total_limit 10 \
    --learning_rate 1e-6 \
    --weight_decay 0.1 \
    --adam_beta2 0.95 \
    --warmup_ratio 0.01 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --gradient_checkpointing true \
    --deepspeed ds_config_zero3.json \
    --report_to "tensorboard" 

### 运行环境 | Environment

```Markdown
- OS:Ubuntu 22.04
- Python:3.10
- Transformers:4.40.0
- PyTorch:2.1.2
- CUDA (`python -c 'import torch; print(torch.version.cuda)'`):12.1
```

**Comment by y-x-x123** [comment]
请问解决了吗

**Comment by weit123** [comment]
我遇到了相同的问题，请问有好的解决方法吗

**Comment by qyc-98** [comment]
minicpm2.0 因为resampler的attention模块等不兼容deepspeed zero3 所以不能用zero3训练

**Comment by qyc-98** [comment]
请发一下您的数据样例

**Comment by padmalcom** [comment]
For all those who are running into this: Replace the parameter "--deepspeed ds_config_zero3.json" by "--deepspeed ds_config_zero2.json" when calling "finetune_ds.sh".
