### ISSUE TITLE
redmi k70 16GB使用MiniCPM-V时报错

### ISSUE THREAD

**Issue by spcxtesla** [OpenBMB/MiniCPM-V#60]
MLCChat failed

Stack trace:
org.apache.tvm.Base$TVMError: TVMError: OpenCL build error for device=0x78b138eaa8
Error: CL_OUT_OF_HOST_MEMORY
Pass
Stack trace:
  File "/Users/acha/Desktop/mlc-MiniCPM/3rdparty/tvm/src/runtime/library_module.cc", line 78

	at org.apache.tvm.Base.checkCall(Base.java:173)
	at org.apache.tvm.Function.invoke(Function.java:130)
	at com.modelbest.mlcllm.ChatModule.image(ChatModule.java:64)
	at com.modelbest.minicpm.AppViewModel$ChatState$requestImage$f$1$1.invoke(AppViewModel.kt:637)
	at com.modelbest.minicpm.AppViewModel$ChatState$requestImage$f$1$1.invoke(AppViewModel.kt:637)
	at com.modelbest.minicpm.AppViewModel$ChatState.callBackend(AppViewModel.kt:516)
	at com.modelbest.minicpm.AppViewModel$ChatState.requestImage$lambda$4(AppViewModel.kt:637)
	at com.modelbest.minicpm.AppViewModel$ChatState.$r8$lambda$-81FfOHgL43Kw6mcY6rLiYQKEuE(Unknown Source:0)
	at com.modelbest.minicpm.AppViewModel$ChatState$$ExternalSyntheticLambda2.run(Unknown Source:12)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

Error message:
TVMError: OpenCL build error for device=0x78b138eaa8
Error: CL_OUT_OF_HOST_MEMORY
Pass
Stack trace:
  File "/Users/acha/Desktop/mlc-MiniCPM/3rdparty/tvm/src/runtime/library_module.cc", line 78

**Comment by spcxtesla** [comment]
请问支持高通骁龙8 Gen2（CPU架构：Cortex-X3,Cortex-A715,Cortex-A710 GPU型号：Adreno 740）吗？

**Comment by Achazwl** [comment]
理论上支持，可以直接安装我们的 APK 测试 (https://github.com/OpenBMB/mlc-MiniCPM/?tab=readme-ov-file#android-apk)
另外上面提到的基于 CPU 的框架 llama.cpp 的适配我们已经跑通 (https://github.com/ggerganov/llama.cpp/pull/6919)
