### ISSUE TITLE
BnB 8bit 在线量化报错

### ISSUE THREAD

**Issue by QwertyJack** [OpenBMB/MiniCPM-V#95]
MiniCPM-V 赞一个🆙

`web_demo_2.5.py` 修改如下：

```python
...
model = AutoModel.from_pretrained(model_path, trust_remote_code=True, device_map='auto', load_in_4bit=True)
model.eval()
...
```

执行报错：

```
Traceback (most recent call last):
  File "/home/jack/git/MiniCPM-V/app.py", line 131, in chat
    answer = model.chat(
             ^^^^^^^^^^^
  File "/home/jack/.cache/huggingface/modules/transformers_modules/MiniCPM-Llama3-V-2_5/modeling_minicpmv.py", line 416, in chat
    res, vision_hidden_states = self.generate(
                                ^^^^^^^^^^^^^^
  File "/home/jack/.cache/huggingface/modules/transformers_modules/MiniCPM-Llama3-V-2_5/modeling_minicpmv.py", line 326, in generate
    ) = self.get_vllm_embedding(model_inputs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/.cache/huggingface/modules/transformers_modules/MiniCPM-Llama3-V-2_5/modeling_minicpmv.py", line 92, in get_vllm_embedding
    vision_embedding = self.resampler(vision_embedding, tgt_sizes)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/.conda/envs/cpm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/.conda/envs/cpm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/.conda/envs/cpm/lib/python3.11/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/.cache/huggingface/modules/transformers_modules/MiniCPM-Llama3-V-2_5/resampler.py", line 150, in forward
    out = self.attn(
          ^^^^^^^^^^
  File "/home/jack/.conda/envs/cpm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/.conda/envs/cpm/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/.conda/envs/cpm/lib/python3.11/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/.conda/envs/cpm/lib/python3.11/site-packages/torch/nn/modules/activation.py", line 1241, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jack/.conda/envs/cpm/lib/python3.11/site-packages/torch/nn/functional.py", line 5413, in multi_head_attention_forward
    attn_output = linear(attn_output, out_proj_weight, out_proj_bias)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: self and mat2 must have the same dtype, but got Half and Char
<Assistant>: Error, please retry
```

**Comment by QwertyJack** [comment]
研究了一下官方提供的 bnb-nf4 量化，需要指定 `llm_int8_skip_modules`，测试 ok

```python
# web_demo_2.5.py
# load in bnb-8bit quantization
...
from transformers import AutoModel, AutoTokenizer, BitsAndBytesConfig

q_config = BitsAndBytesConfig(
    load_in_8bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=torch.float16,
    llm_int8_skip_modules=['out_proj', 'kv_proj', 'lm_head'],
)
model = AutoModel.from_pretrained('openbmb/MiniCPM-Llama3-V-2_5', trust_remote_code=True, quantization_config=q_config)
...
```

**Comment by QwertyJack** [comment]
Btw，8bit 占用 10GB 显存

**Comment by zenjieli** [comment]
> 官方提供的 bnb-nf4 量化

Thanks for the hint! By the way, where did you see the bnb-nf4 quantization documentation?
